# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exif.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExifReader(object):
    def setupUi(self, ExifReader):
        ExifReader.setObjectName("ExifReader")
        ExifReader.resize(608, 608)
        font = QtGui.QFont()
        font.setPointSize(10)
        ExifReader.setFont(font)
        ExifReader.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(ExifReader)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(1200, 1200))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"border: 4px dashed")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.tableView = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(200, 200))
        self.tableView.setMaximumSize(QtCore.QSize(800, 10000))
        self.tableView.setObjectName("tableView")
        self.tableView.setColumnCount(0)
        self.tableView.setRowCount(0)
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.left_rotate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_rotate.sizePolicy().hasHeightForWidth())
        self.left_rotate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.left_rotate.setFont(font)
        self.left_rotate.setShortcut("")
        self.left_rotate.setObjectName("left_rotate")
        self.verticalLayout.addWidget(self.left_rotate)
        self.right_rotate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_rotate.sizePolicy().hasHeightForWidth())
        self.right_rotate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.right_rotate.setFont(font)
        self.right_rotate.setObjectName("right_rotate")
        self.verticalLayout.addWidget(self.right_rotate)
        self.nextImgButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextImgButton.sizePolicy().hasHeightForWidth())
        self.nextImgButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nextImgButton.setFont(font)
        self.nextImgButton.setObjectName("nextImgButton")
        self.verticalLayout.addWidget(self.nextImgButton)
        self.previousImgButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousImgButton.sizePolicy().hasHeightForWidth())
        self.previousImgButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.previousImgButton.setFont(font)
        self.previousImgButton.setObjectName("previousImgButton")
        self.verticalLayout.addWidget(self.previousImgButton)
        self.aprimappa = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aprimappa.sizePolicy().hasHeightForWidth())
        self.aprimappa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aprimappa.setFont(font)
        self.aprimappa.setAutoDefault(False)
        self.aprimappa.setObjectName("aprimappa")
        self.verticalLayout.addWidget(self.aprimappa)
        self.load = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load.sizePolicy().hasHeightForWidth())
        self.load.setSizePolicy(sizePolicy)
        self.load.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.load.setFont(font)
        self.load.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.load.setObjectName("load")
        self.verticalLayout.addWidget(self.load)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        ExifReader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ExifReader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ExifReader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ExifReader)
        self.statusbar.setObjectName("statusbar")
        ExifReader.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(ExifReader)
        self.action_Quit.setObjectName("action_Quit")
        self.action_About = QtWidgets.QAction(ExifReader)
        self.action_About.setObjectName("action_About")
        self.actionLoad_Multiple_Images = QtWidgets.QAction(ExifReader)
        self.actionLoad_Multiple_Images.setObjectName("actionLoad_Multiple_Images")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuFile.addAction(self.actionLoad_Multiple_Images)
        self.menuAbout.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ExifReader)
        QtCore.QMetaObject.connectSlotsByName(ExifReader)

    def retranslateUi(self, ExifReader):
        _translate = QtCore.QCoreApplication.translate
        ExifReader.setWindowTitle(_translate("ExifReader", "MainWindow"))
        self.label.setText(_translate("ExifReader", "Insert image here"))
        self.left_rotate.setText(_translate("ExifReader", " &Left Rotate"))
        self.right_rotate.setText(_translate("ExifReader", "&Right Rotate"))
        self.nextImgButton.setText(_translate("ExifReader", "Next Image"))
        self.previousImgButton.setText(_translate("ExifReader", "Previous Image"))
        self.aprimappa.setText(_translate("ExifReader", "Open map"))
        self.load.setText(_translate("ExifReader", "Load Image "))
        self.menuFile.setTitle(_translate("ExifReader", "&File"))
        self.menuAbout.setTitle(_translate("ExifReader", "&Help"))
        self.action_Quit.setText(_translate("ExifReader", "&Quit"))
        self.action_About.setText(_translate("ExifReader", "&About"))
        self.actionLoad_Multiple_Images.setText(_translate("ExifReader", "Load Multiple Images"))

